### ISSUE TITLE
A workflow ID means different things on different deployments, and nothing records which one ran

### ISSUE THREAD

**Issue by NeuralEmpowerment** [syntropic137/syntropic137#1264]
## What

`syn workflow run` never says which deployment it dispatched to, and the same workflow ID resolves to **materially different workflows** on different deployments. Together those two facts let a run be sent to the wrong host and produce a verdict that looks valid and is not.

## Reproduction (lived, 2026-09-09)

Dispatching three PR reviews intended for the VPS:

```
$ syn workflow run sdlc-pr-review-v1 -R syntropic137/syntropic137 -t "..."
Workflow execution started
  Execution ID: exec-c803af9578c6
```

That output names no host. `SYN_API_URL` was set to the Mac mini (`100.112.178.5`), not the VPS (`100.114.86.77`), so all three landed on the wrong deployment. It surfaced only because the returned ID 404s on the host I then queried:

```
GET http://100.114.86.77:8137/api/v1/executions/exec-c803af9578c6
-> 404 {"detail":"Execution not found: exec-c803af9578c6"}
```

## The part that makes it dangerous

`sdlc-pr-review-v1` is not the same workflow on the two deployments:

| phase | VPS | Mac mini |
|---|---|---|
| Map what the change touches | opus / claude | sonnet / claude |
| **Try to falsify the claim** | **gpt-5.6-sol / codex** | **sonnet / claude** |
| Write the verdict | sonnet / claude | sonnet / claude |

The mini's review is **single-model**. The whole point of this workflow is that the falsification phase runs on a different model from the one that wrote the code; on the mini that property is silently absent.

So the failure mode is not "the run went to the wrong box." It is: **a same-model review is returned in the shape of a cross-model certification.** Nothing in the execution record marks the difference. Had I not compared the two definitions by hand, three PRs could have been merged on verdicts that did not carry the property the merge rule requires.

I caught it and cancelled all three. The next person may not.

## Why this is the familiar shape

Same class as #1263 and the fail-open gates in #1239: the interface reports success without the property the caller was relying on. Here the missing property is provenance.

## Suggested direction

1. **`syn workflow run` should print the target host** it dispatched to, before the execution ID. One line, and this class of error becomes self-announcing.
2. **The execution record should carry the resolved phase models** (provider + model per phase, as executed). Then a verdict's provenance is checkable after the fact instead of requiring someone to remember to diff two live deployments. Right now `GET /executions/{id}` exposes no such field, which is also what makes stale-definition questions unanswerable in general.
3. Consider whether a workflow ID that means different things on different deployments should be the same ID at all - a version or content hash in the record would make divergence visible rather than inferable.

(2) is the one that matters. (1) is convenience; (2) is what makes a certification auditable.

**Comment by NeuralEmpowerment** [comment]
## Most of this is already recorded. #1263 makes it reachable.

I filed this after hand-diffing two live deployments to discover that `sdlc-pr-review-v1` runs `gpt-5.6-sol/codex` on the VPS and `sonnet/claude` on the Mac mini - and concluded "nothing records which one ran".

**That was wrong.** Verified against the running system today: a session already carries the provenance.

```
execution_id     exec-7836560464e4
agent_provider   claude
agent_model      opus
phase_id / phase_display
agent_model_display
```

Across 40 recent sessions, **34 carry a populated `agent_model`**, and the values are exactly what an audit needs:

```
claude  opus           phase=Revise
codex   gpt-5.6-sol    phase=Cross Model Review
claude  opus           phase=Plan
claude  opus           phase=Research
claude  sonnet         phase=Open Pr
```

That is a per-phase record of which model actually ran, on the execution's own sessions - precisely the question I could not answer without diffing two deployments by hand.

**What was missing was not the data. It was the query.** `GET /api/v1/sessions` had no `execution_id` filter, so "which models ran in execution X" could not be asked. #1263 adds it (PR #1277), and once merged this becomes a single request.

## The residual gap, which is narrower and more interesting

All **6** sessions without an `agent_model` share one status: `failed`.

`agent_model` comes from the Lane 2 cost projection, which is populated from observed usage. A phase that dies before the agent produces any usage therefore records **no model at all** - and that is exactly the case where an operator most wants to know what was configured to run.

So the accurate statement of this issue is not "provenance is missing" but:

> **Provenance is recorded from what the agent DID, not from what the phase was CONFIGURED to do, so it is absent precisely when the phase failed.**

That is the same shape as several defects already tracked here: the record exists when things work and disappears when they do not.

## Revised scope

1. **Merge #1277.** That alone makes existing provenance queryable and closes the original complaint.
2. **Then decide** whether the *configured* provider/model should be stamped on the execution at provision time, independent of Lane 2. That is a small domain addition and a real decision, not an oversight - Lane 1 deliberately does not carry cost-adjacent fields (#695), and model selection sits close to that line.

Reducing this issue to (2) and marking (1) as its prerequisite.
